---
plugins:
  - rubocop-rspec

RSpec/DescribedClassModuleWrapping:
  Enabled: true

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'

RSpec/ExampleWithoutDescription:
  EnforcedStyle: single_line_only

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5
